import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Shield, UserPlus } from "lucide-react";
import { useState } from "react";
import { useSession } from "../auth/AuthContext";
import { Dialog, ErrorNotice, Field, FormActions, JsonForm, Loading, PageHeader, Status } from "../components/ui";
import { api, post } from "../lib/api";
import { shortDate } from "../lib/format";
import type { Member, Role } from "../types";

export default function AdminPage() { const session = useSession(); const client = useQueryClient(); const [memberOpen, setMemberOpen] = useState(false); const [roleOpen, setRoleOpen] = useState(false); const roles = useQuery({ queryKey: ["roles"], queryFn: () => api<Role[]>(session, "/api/v1/organizations/current/roles") }); const members = useQuery({ queryKey: ["members"], queryFn: () => api<Member[]>(session, "/api/v1/organizations/current/members") }); const invite = useMutation({ mutationFn: (body: unknown) => post(session, "/api/v1/organizations/current/members", body), onSuccess: () => { void client.invalidateQueries({ queryKey: ["members"] }); setMemberOpen(false); } }); const createRole = useMutation({ mutationFn: (body: unknown) => post(session, "/api/v1/organizations/current/roles", body), onSuccess: () => { void client.invalidateQueries({ queryKey: ["roles"] }); setRoleOpen(false); } }); if (roles.isLoading || members.isLoading) return <Loading/>; if (roles.error || members.error) return <ErrorNotice error={roles.error || members.error}/>;
  return <><PageHeader eyebrow="Organization administration" title="Team and access" description="Invite people and assign only the permissions required for their work." action={<div className="button-group"><button className="button button-secondary" onClick={() => setRoleOpen(true)}><Shield size={16}/>New role</button><button className="button button-primary" onClick={() => setMemberOpen(true)}><UserPlus size={16}/>Invite member</button></div>}/><div className="admin-grid"><section className="panel span-2"><header className="panel-header"><div><p className="eyebrow">People</p><h2>{members.data!.length} members</h2></div></header><div className="member-list">{members.data!.map((member) => <article key={member.membership_id}><div className="avatar">{member.display_name.slice(0, 2).toUpperCase()}</div><div><strong>{member.display_name}</strong><span>{member.email}</span></div><div className="member-roles">{member.role_ids.map((id) => <span className="tag" key={id}>{roles.data!.find((role) => role.id === id)?.name || "Role"}</span>)}</div><div><Status value={member.status}/><small>Joined {shortDate(member.joined_at)}</small></div></article>)}</div></section><section className="panel"><header className="panel-header"><div><p className="eyebrow">Access model</p><h2>Roles</h2></div></header><div className="role-list">{roles.data!.map((role) => <article key={role.id}><div><strong>{role.name}</strong>{role.is_system && <Shield size={14}/>}</div><p>{role.description || "Custom organization role"}</p><span>{role.permission_codes.length} permissions</span></article>)}</div></section></div>
  <Dialog open={memberOpen} onClose={() => setMemberOpen(false)} title="Invite member" description="They can activate this invitation only with the same verified email at your identity provider."><JsonForm onSubmit={(data) => invite.mutate({ email: data.get("email"), display_name: data.get("name"), role_ids: [data.get("roleId")] })}><Field label="Full name"><input name="name" required autoFocus/></Field><Field label="Work email"><input name="email" type="email" required/></Field><Field label="Role"><select name="roleId" required>{roles.data!.map((role) => <option value={role.id} key={role.id}>{role.name}</option>)}</select></Field>{invite.error && <p className="form-error">{invite.error.message}</p>}<FormActions pending={invite.isPending} submit="Send invitation" onCancel={() => setMemberOpen(false)}/></JsonForm></Dialog>
  <Dialog open={roleOpen} onClose={() => setRoleOpen(false)} title="Create role" description="Use exact permission codes from the backend permission catalog."><JsonForm onSubmit={(data) => createRole.mutate({ name: data.get("name"), description: data.get("description") || null, permission_codes: String(data.get("permissions")).split(/[\s,]+/).filter(Boolean) })}><Field label="Role name"><input name="name" required autoFocus/></Field><Field label="Description"><input name="description"/></Field><Field label="Permission codes" hint="Separate codes with commas or spaces"><textarea name="permissions" required rows={5} placeholder="requisitions.read, requisitions.write, suppliers.read"/></Field>{createRole.error && <p className="form-error">{createRole.error.message}</p>}<FormActions pending={createRole.isPending} submit="Create role" onCancel={() => setRoleOpen(false)}/></JsonForm></Dialog></>;
}
