import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Link } from "react-router-dom";
import { useSession } from "../auth/AuthContext";
import { Dialog, EmptyState, ErrorNotice, Field, FormActions, JsonForm, Loading, PageHeader, Status } from "../components/ui";
import { api, post } from "../lib/api";
import type { ListResponse } from "../types";

export type Policy = { id: string; name: string; status: string; required_approvals: number; minimum_amount: string; maximum_amount: string | null; prohibit_self_approval: boolean };
export type Approval = { id: string; requisition_id: string; status: string; requested_amount: string; currency: string; approval_count: number; required_approvals: number; decisions: Array<{ id: string; decision: string; comment?: string }> };

export default function ApprovalsPage() {
  const session = useSession(); const client = useQueryClient(); const [open, setOpen] = useState(false); const [error, setError] = useState("");
  const policies = useQuery({ queryKey: ["approval-policies"], queryFn: () => api<ListResponse<Policy>>(session, "/api/v1/approval-policies") });
  const requests = useQuery({ queryKey: ["approval-requests"], queryFn: () => api<ListResponse<Approval>>(session, "/api/v1/approval-requests") });
  const change = useMutation({ mutationFn: ({ path, body }: { path: string; body: unknown }) => post(session, path, body), onSuccess: () => { setError(""); setOpen(false); void client.invalidateQueries({ queryKey: ["approval-policies"] }); void client.invalidateQueries({ queryKey: ["approval-requests"] }); void client.invalidateQueries({ queryKey: ["requisitions"] }); }, onError: reason => setError(reason instanceof Error ? reason.message : "Action failed") });
  return <><PageHeader eyebrow="Decision control" title="Approvals" description="Set the approval policy and decide submitted purchase requests." action={<button className="button button-primary" onClick={() => setOpen(true)}>New policy</button>}/>{error && <p className="form-error">{error}</p>}
    <section className="panel" style={{ padding: 24, marginBottom: 20 }}><h2>Approval policies</h2>{policies.isLoading ? <Loading/> : policies.error ? <ErrorNotice error={policies.error}/> : !policies.data?.items.length ? <EmptyState title="No policy" detail="Create a policy before requesting approval."/> : policies.data.items.map(item => <p key={item.id}><strong>{item.name}</strong> · {item.required_approvals} decision(s) · minimum {item.minimum_amount} · <Status value={item.status}/></p>)}</section>
    <section className="panel" style={{ padding: 24 }}><h2>Decision inbox</h2>{requests.isLoading ? <Loading/> : requests.error ? <ErrorNotice error={requests.error}/> : !requests.data?.items.length ? <EmptyState title="No requests" detail="Submit a requisition and route it for approval."/> : requests.data.items.map(item => <article key={item.id} style={{ borderTop: "1px solid var(--border)", padding: "16px 0" }}><Link to={`/requisitions/${item.requisition_id}`}>Requisition {item.requisition_id.slice(0, 8)}</Link> · {item.requested_amount} {item.currency} · <Status value={item.status}/> · {item.approval_count}/{item.required_approvals} approvals{item.status === "pending" && <span style={{ display: "inline-flex", gap: 8, marginLeft: 12 }}><button className="button button-primary" disabled={change.isPending} onClick={() => change.mutate({ path: `/api/v1/approval-requests/${item.id}/approve`, body: { comment: "Approved after review" } })}>Approve</button><button className="button button-ghost" disabled={change.isPending} onClick={() => { const comment = window.prompt("Reason for rejection"); if (comment) change.mutate({ path: `/api/v1/approval-requests/${item.id}/reject`, body: { comment } }); }}>Reject</button></span>}{item.decisions.map(decision => <p key={decision.id}>{decision.decision}: {decision.comment}</p>)}</article>)}</section>
    <Dialog open={open} title="New approval policy" description="A new version supersedes an active policy with the same name." onClose={() => setOpen(false)}><JsonForm onSubmit={data => change.mutate({ path: "/api/v1/approval-policies", body: { name: data.get("name"), minimum_amount: data.get("minimum"), maximum_amount: data.get("maximum") || null, required_approvals: Number(data.get("required")), prohibit_self_approval: Boolean(data.get("noSelf")), rules: {} } })}><Field label="Policy name"><input name="name" required minLength={2}/></Field><Field label="Minimum amount"><input name="minimum" type="number" min="0" step="0.01" defaultValue="0" required/></Field><Field label="Maximum amount (optional)"><input name="maximum" type="number" min="0" step="0.01"/></Field><Field label="Required approvers"><input name="required" type="number" min="1" max="20" defaultValue="1" required/></Field><label className="check-field"><input type="checkbox" name="noSelf" defaultChecked/>Prevent self-approval</label><FormActions pending={change.isPending} submit="Create policy" onCancel={() => setOpen(false)}/></JsonForm></Dialog>
  </>;
}
