import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus } from "lucide-react";
import { useState } from "react";
import { useSession } from "../auth/AuthContext";
import { Dialog, EmptyState, ErrorNotice, Field, FormActions, JsonForm, Loading, PageHeader, Status } from "../components/ui";
import { api, post } from "../lib/api";
import { money, shortDate } from "../lib/format";
import type { Budget, ListResponse } from "../types";

export default function BudgetsPage() { const session = useSession(); const client = useQueryClient(); const [open, setOpen] = useState(false); const query = useQuery({ queryKey: ["budgets"], queryFn: () => api<ListResponse<Budget>>(session, "/api/v1/budgets?limit=100") }); const create = useMutation({ mutationFn: (body: unknown) => post(session, "/api/v1/budgets", body), onSuccess: () => { void client.invalidateQueries({ queryKey: ["budgets"] }); setOpen(false); } });
  return <><PageHeader eyebrow="Financial control" title="Budgets" description="Allocated, reserved and committed funds from the append-only ledger." action={<button className="button button-primary" onClick={() => setOpen(true)}><Plus size={16}/>New budget</button>}/>{query.isLoading ? <Loading/> : query.error ? <ErrorNotice error={query.error}/> : !query.data?.items.length ? <EmptyState title="No budgets configured" detail="Create a budget before routing requisitions for financial approval."/> : <div className="budget-grid">{query.data.items.map((item) => { const total = Number(item.available) + Number(item.reserved) + Number(item.committed) + Number(item.consumed); const used = total ? ((total - Number(item.available)) / total) * 100 : 0; return <article className="budget-card" key={item.id}><header><div><span className="mono-label">{item.code}</span><h3>{item.name}</h3></div><Status value={item.status}/></header><strong className="budget-amount">{money(item.available, item.currency)}</strong><span>available</span><div className="budget-bar"><i style={{ width: `${Math.min(100, used)}%` }}/></div><dl><div><dt>Reserved</dt><dd>{money(item.reserved, item.currency)}</dd></div><div><dt>Committed</dt><dd>{money(item.committed, item.currency)}</dd></div></dl><footer>{shortDate(item.period_start)} — {shortDate(item.period_end)}</footer></article>; })}</div>}
  <Dialog open={open} onClose={() => setOpen(false)} title="Create budget" description="The initial allocation creates the first immutable ledger entry."><JsonForm onSubmit={(data) => create.mutate({ code: String(data.get("code")).toUpperCase(), name: data.get("name"), currency: data.get("currency"), period_start: data.get("start"), period_end: data.get("end"), initial_allocation: data.get("allocation") })}><div className="form-grid"><Field label="Budget code"><input name="code" required pattern="[A-Za-z0-9_-]+" autoFocus/></Field><Field label="Budget name"><input name="name" required/></Field><Field label="Currency"><select name="currency" defaultValue="PKR"><option>PKR</option><option>USD</option><option>EUR</option></select></Field><Field label="Initial allocation"><input name="allocation" type="number" min="0" step="0.01" required/></Field><Field label="Period start"><input name="start" type="date" required/></Field><Field label="Period end"><input name="end" type="date" required/></Field></div>{create.error && <p className="form-error">{create.error.message}</p>}<FormActions pending={create.isPending} submit="Create budget" onCancel={() => setOpen(false)}/></JsonForm></Dialog></>;
}
