import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Download, Headphones, LifeBuoy, Send } from "lucide-react";
import { useSession } from "../auth/AuthContext";
import { ErrorNotice, Field, Loading, PageHeader, Status } from "../components/ui";
import { api, post } from "../lib/api";

type Overview = { subscription: { plan_code: string; status: string; seat_limit: number; storage_limit_bytes: number; ai_run_limit_monthly: number }; active_members: number; stored_bytes: number; open_support_cases: number; seat_usage_percent: number; storage_usage_percent: number };
type Case = { id: string; case_number: string; subject: string; priority: string; status: string };

export default function CommercialPage() {
  const session = useSession(); const cache = useQueryClient();
  const overview = useQuery({ queryKey: ["commercial"], queryFn: () => api<Overview>(session, "/api/v1/commercial/overview") });
  const cases = useQuery({ queryKey: ["support-cases"], queryFn: () => api<Case[]>(session, "/api/v1/commercial/support-cases") });
  const create = useMutation({ mutationFn: (body: unknown) => post(session, "/api/v1/commercial/support-cases", body), onSuccess: () => void cache.invalidateQueries({ queryKey: ["support-cases"] }) });
  const exportData = useMutation({ mutationFn: () => post<Record<string, unknown>>(session, "/api/v1/commercial/data-export", {}), onSuccess: payload => { const url = URL.createObjectURL(new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = `procurex-export-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(url); } });
  if (overview.isLoading || cases.isLoading) return <Loading/>;
  if (overview.error || cases.error) return <ErrorNotice error={overview.error || cases.error}/>;
  const value = overview.data!;
  return <><PageHeader eyebrow="Account and service" title="Plan, usage and support" description="Understand your limits, export your records, and keep support requests in an auditable workspace." action={<button className="button button-secondary" onClick={() => exportData.mutate()} disabled={exportData.isPending}><Download size={16}/>{exportData.isPending ? "Preparing…" : "Export organization data"}</button>}/><div className="metric-grid"><article><span>Current plan</span><strong>{value.subscription.plan_code}</strong><small><Status value={value.subscription.status}/></small></article><article><span>Seats</span><strong>{value.active_members} / {value.subscription.seat_limit}</strong><small>{value.seat_usage_percent}% used</small></article><article><span>Document storage</span><strong>{(value.stored_bytes / 1048576).toFixed(1)} MB</strong><small>{value.storage_usage_percent}% used</small></article><article><span>Open support</span><strong>{value.open_support_cases}</strong><small>Cases awaiting closure</small></article></div><div className="dashboard-grid"><section className="panel"><header className="panel-header"><div><p className="eyebrow">Support ledger</p><h2>Requests</h2></div><Headphones size={18}/></header>{cases.data!.length ? <div className="record-list">{cases.data!.map(item => <div className="record-row" key={item.id}><div className="record-icon"><LifeBuoy size={16}/></div><div className="record-main"><strong>{item.subject}</strong><span>{item.case_number} · {item.priority}</span></div><Status value={item.status}/></div>)}</div> : <p className="panel-copy">No support cases are open.</p>}</section><section className="panel"><header className="panel-header"><div><p className="eyebrow">Get help</p><h2>Open a case</h2></div></header><form className="form" onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); create.mutate({ subject: data.get("subject"), description: data.get("description"), priority: data.get("priority") }); event.currentTarget.reset(); }}><Field label="Subject"><input name="subject" required minLength={3}/></Field><Field label="Priority"><select name="priority"><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option><option value="low">Low</option></select></Field><Field label="Description"><textarea name="description" required minLength={10} rows={5}/></Field>{create.error && <p className="form-error">{create.error.message}</p>}<button className="button button-primary" disabled={create.isPending}><Send size={15}/>Submit case</button></form></section></div></>;
}
