import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useSession } from "../auth/AuthContext";
import { ErrorNotice, Field as FormField, JsonForm, Loading, PageHeader, Status } from "../components/ui";
import { api, post } from "../lib/api";

type Page = { id: string; page_number: number; text: string; tables: Array<Record<string, unknown>> };
type Parse = { id: string; status: string; pages: Page[]; parser: string; created_at: string };
type Version = { id: string; version: number; original_filename: string; status: string; scans: Array<{ id: string; status: string; scanner: string }>; parses: Parse[] };
type Document = { id: string; title: string; document_type: string; status: string; versions: Version[] };
type Field = { id: string; label: string; field_key: string; raw_value: unknown; normalized_value: unknown; status: string; is_critical: boolean; confidence: string | null; anchors: Array<{ id: string; page_id: string; quoted_text: string | null; cell_range: string | null }>; reviews: Array<{ id: string; action: string; reason: string; reviewed_at: string }> };
type Extraction = { id: string; parse_id: string; revision: number; status: string; schema_name: string; fields: Field[] };

export default function DocumentDetailPage() {
  const { id } = useParams(); const session = useSession(); const client = useQueryClient();
  const [selectedVersion, setSelectedVersion] = useState(""); const [selectedExtraction, setSelectedExtraction] = useState(""); const [error, setError] = useState(""); const [fieldCount, setFieldCount] = useState(1);
  const document = useQuery({ queryKey: ["document", id], queryFn: () => api<Document>(session, `/api/v1/documents/${id}`) });
  const version = document.data?.versions.find(item => item.id === selectedVersion) || document.data?.versions.at(-1);
  const extractions = useQuery({ queryKey: ["document-extractions", version?.id], enabled: Boolean(version), queryFn: () => api<Extraction[]>(session, `/api/v1/documents/versions/${version?.id}/extractions`) });
  const extraction = extractions.data?.find(item => item.id === selectedExtraction) || extractions.data?.[0];
  const parse = version?.parses.find(item => item.id === extraction?.parse_id) || version?.parses.at(-1);
  const change = useMutation({ mutationFn: ({ path, body }: { path: string; body: unknown }) => post(session, path, body), onSuccess: () => { setError(""); void client.invalidateQueries({ queryKey: ["document", id] }); void client.invalidateQueries({ queryKey: ["document-extractions", version?.id] }); }, onError: reason => setError(reason instanceof Error ? reason.message : "Review failed") });
  const download = async () => { if (!version) return; try { const result = await api<{ download_url: string }>(session, `/api/v1/documents/versions/${version.id}/download`); window.location.assign(result.download_url); } catch (reason) { setError(reason instanceof Error ? reason.message : "Download failed"); } };
  const review = (field: Field, action: "verify" | "correct" | "reject") => {
    if (!extraction) return;
    const reason = window.prompt(action === "correct" ? "Reason for correction" : `Reason to ${action} this field`);
    if (!reason) return;
    let normalized_value: unknown = undefined;
    if (action === "correct") {
      const entry = window.prompt("Correct value (JSON or plain text)", String(field.normalized_value ?? field.raw_value ?? ""));
      if (entry === null || !entry.trim()) return;
      try { normalized_value = JSON.parse(entry) as unknown; } catch { normalized_value = entry; }
    }
    change.mutate({ path: `/api/v1/extractions/${extraction.id}/fields/${field.id}/review`, body: { expected_revision: extraction.revision, action, reason, ...(action === "correct" ? { normalized_value } : {}) } });
  };
  if (document.isLoading) return <Loading/>; if (document.error || !document.data) return <ErrorNotice error={document.error}/>;
  const item = document.data;
  return <><Link to="/documents" className="back-link">← Documents</Link><PageHeader eyebrow="Evidence review" title={item.title} description={item.document_type} action={<Status value={item.status}/>}/>{error && <p className="form-error" role="alert">{error}</p>}
    <section className="panel" style={{ padding: 24, marginBottom: 20 }}><h2>Source document</h2><label className="field"><span>Version</span><select value={version?.id || ""} onChange={event => { setSelectedVersion(event.target.value); setSelectedExtraction(""); }}>{item.versions.map(candidate => <option key={candidate.id} value={candidate.id}>v{candidate.version} · {candidate.original_filename} · {candidate.status}</option>)}</select></label>{version && <><p>Scan: {version.scans.map(scan => `${scan.scanner} ${scan.status}`).join(", ") || "Pending"}</p><button className="button button-ghost" onClick={() => void download()}>Download verified original</button></>}</section>
    {version?.status === "parsed" && parse?.status === "completed" && <section className="panel" style={{ padding: 24, marginBottom: 20 }}><h2>Stage fields for review</h2><p>Copy an exact source excerpt from a parsed page. Staged fields are proposals until a reviewer verifies them.</p><JsonForm onSubmit={data => change.mutate({ path: `/api/v1/documents/versions/${version.id}/manual-extractions`, body: { parse_id: parse.id, schema_name: "manual_review", fields: Array.from({ length: fieldCount }, (_, index) => ({ field_key: data.get(`key-${index}`), label: data.get(`label-${index}`), value: data.get(`value-${index}`), page_number: Number(data.get(`page-${index}`)), quoted_text: data.get(`quote-${index}`), is_critical: Boolean(data.get(`critical-${index}`)) })) } })}>{Array.from({ length: fieldCount }, (_, index) => <div key={index} className="form-grid"><FormField label={`Field ${index + 1} key`}><input name={`key-${index}`} pattern="[a-z][a-z0-9_.]*" placeholder="unit_price" required/></FormField><FormField label="Label"><input name={`label-${index}`} required/></FormField><FormField label="Value"><input name={`value-${index}`} required/></FormField><FormField label="Source page"><select name={`page-${index}`} required>{parse.pages.map(page => <option key={page.id} value={page.page_number}>{page.page_number}</option>)}</select></FormField><FormField label="Exact quoted text"><textarea name={`quote-${index}`} required/></FormField><label className="check-field"><input type="checkbox" name={`critical-${index}`}/>Critical field</label></div>)}<button type="button" className="button button-ghost" onClick={() => setFieldCount(count => Math.min(count + 1, 100))}>Add field</button><button className="button button-primary" disabled={change.isPending}>Stage for review</button></JsonForm></section>}
    <div className="detail-grid"><section className="panel span-2" style={{ padding: 24 }}><h2>Parsed source</h2>{parse?.pages.length ? parse.pages.map(page => <article key={page.id} id={`page-${page.id}`} style={{ padding: "12px 0", borderTop: "1px solid var(--border)" }}><h3>Page {page.page_number}</h3><pre style={{ whiteSpace: "pre-wrap", overflowWrap: "anywhere", maxHeight: 500, overflow: "auto" }}>{page.text}</pre>{page.tables.length > 0 && <details><summary>Extracted tables</summary><pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify(page.tables, null, 2)}</pre></details>}</article>) : <p>No parsed pages are available yet. Check the scan and parser status.</p>}</section>
      <section className="panel" style={{ padding: 24 }}><h2>Extracted fields</h2>{extractions.isLoading ? <Loading/> : extractions.error ? <ErrorNotice error={extractions.error}/> : !extraction ? <p>No extraction is available for this version yet.</p> : <><label className="field"><span>Extraction</span><select value={extraction.id} onChange={event => setSelectedExtraction(event.target.value)}>{extractions.data?.map(candidate => <option key={candidate.id} value={candidate.id}>{candidate.schema_name} · {candidate.status}</option>)}</select></label><p><Status value={extraction.status}/> Revision {extraction.revision}</p>{extraction.fields.map(field => <article key={field.id} style={{ padding: "14px 0", borderTop: "1px solid var(--border)" }}><h3>{field.label} {field.is_critical && <small>(critical)</small>}</h3><p>Raw: {JSON.stringify(field.raw_value ?? null)}</p><p>Reviewed value: {JSON.stringify(field.normalized_value ?? null)}</p><p><Status value={field.status}/> {field.confidence && `· Confidence ${field.confidence}`}</p>{field.anchors.map(anchor => <p key={anchor.id}>Source: <a href={`#page-${anchor.page_id}`}>{parse?.pages.find(page => page.id === anchor.page_id)?.page_number ? `Page ${parse.pages.find(page => page.id === anchor.page_id)?.page_number}` : "Page"}</a> · {anchor.quoted_text || anchor.cell_range || "Visual region"}</p>)}{field.reviews.map(decision => <p key={decision.id}>{decision.action}: {decision.reason}</p>)}{extraction.status !== "completed" && <div style={{ display: "flex", gap: 6, flexWrap: "wrap" }}><button className="button button-ghost" disabled={change.isPending} onClick={() => review(field, "verify")}>Verify</button><button className="button button-ghost" disabled={change.isPending} onClick={() => review(field, "correct")}>Correct</button><button className="button button-ghost" disabled={change.isPending} onClick={() => review(field, "reject")}>Reject</button></div>}</article>)}{extraction.status !== "completed" && <button className="button button-primary" disabled={change.isPending} onClick={() => change.mutate({ path: `/api/v1/extractions/${extraction.id}/finalize`, body: { expected_revision: extraction.revision } })}>Finalize reviewed extraction</button>}</>}</section></div>
  </>;
}
