import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { FileText, Upload } from "lucide-react";
import { useState } from "react";
import { useSession } from "../auth/AuthContext";
import { Dialog, EmptyState, ErrorNotice, Field, FormActions, JsonForm, Loading, PageHeader, Status } from "../components/ui";
import { api, post } from "../lib/api";
import { relativeDate } from "../lib/format";
import type { DocumentRecord, ListResponse } from "../types";

const digest = async (file: File) => Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", await file.arrayBuffer()))).map((byte) => byte.toString(16).padStart(2, "0")).join("");

export default function DocumentsPage() { const session = useSession(); const client = useQueryClient(); const [open, setOpen] = useState(false); const query = useQuery({ queryKey: ["documents"], queryFn: () => api<ListResponse<DocumentRecord>>(session, "/api/v1/documents?limit=100") }); const upload = useMutation({ mutationFn: async ({ file, title, documentType }: { file: File; title: string; documentType: string }) => { const intent = await post<{ document_id: string; document_version_id: string; upload_url: string; upload_parameters: Record<string, string | number> }>(session, "/api/v1/documents/upload-intents", { title, document_type: documentType, original_filename: file.name, media_type: file.type, byte_size: file.size, sha256: await digest(file) }); const form = new FormData(); Object.entries(intent.upload_parameters).forEach(([key, value]) => form.append(key, String(value))); form.append("file", file); const cloud = await fetch(intent.upload_url, { method: "POST", body: form }); if (!cloud.ok) throw new Error("Cloud storage rejected the upload."); const result = await cloud.json() as Record<string, unknown>; return post(session, `/api/v1/documents/${intent.document_id}/versions/${intent.document_version_id}/complete-upload`, { cloudinary_asset_id: result.asset_id, public_id: result.public_id, resource_type: "raw", delivery_type: "authenticated", provider_version: result.version, format: result.format || null, byte_size: result.bytes, signature: result.signature }); }, onSuccess: () => { void client.invalidateQueries({ queryKey: ["documents"] }); setOpen(false); } });
  return <><PageHeader eyebrow="Evidence vault" title="Documents" description="Immutable originals move through quarantine, scanning, parsing and review." action={<button className="button button-primary" onClick={() => setOpen(true)}><Upload size={16}/>Upload document</button>}/>{query.isLoading ? <Loading/> : query.error ? <ErrorNotice error={query.error}/> : !query.data?.items.length ? <EmptyState title="No documents uploaded" detail="Upload supplier evidence, quotations or supporting records."/> : <div className="document-list">{query.data.items.map((item) => { const version = item.versions.at(-1); return <article key={item.id}><div className="file-type"><FileText size={21}/><span>{version?.original_filename.split(".").at(-1)?.toUpperCase()}</span></div><div><strong>{item.title}</strong><span>{version?.original_filename} · {version ? `${(version.byte_size / 1024 / 1024).toFixed(2)} MB` : "No file"}</span></div><div><span className="mono-label">{item.document_type}</span><small>Updated {relativeDate(item.updated_at)}</small></div><Status value={version?.status || item.status}/></article>; })}</div>}
  <Dialog open={open} onClose={() => setOpen(false)} title="Upload document" description="Supported: PDF, DOCX, XLSX, JPEG and PNG. Files remain inaccessible until scanning succeeds."><JsonForm onSubmit={(data) => { const file = data.get("file"); if (file instanceof File) upload.mutate({ file, title: String(data.get("title")), documentType: String(data.get("documentType")) }); }}><Field label="Document title"><input name="title" required autoFocus/></Field><Field label="Document type"><select name="documentType" defaultValue="supplier_quote"><option value="supplier_quote">Supplier quote</option><option value="requisition_support">Requisition support</option><option value="supplier_certificate">Supplier certificate</option><option value="invoice">Invoice</option><option value="delivery_evidence">Delivery evidence</option></select></Field><Field label="File" hint="Maximum 25 MB"><input name="file" type="file" required accept=".pdf,.docx,.xlsx,.jpg,.jpeg,.png"/></Field>{upload.error && <p className="form-error">{upload.error.message}</p>}<FormActions pending={upload.isPending} submit="Upload securely" onCancel={() => setOpen(false)}/></JsonForm></Dialog></>;
}
