import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { useSession } from "../auth/AuthContext";
import { Dialog, EmptyState, ErrorNotice, Field, FormActions, JsonForm, Loading, PageHeader, Status } from "../components/ui";
import { api, post } from "../lib/api";
import { money, relativeDate } from "../lib/format";
import type { ListResponse, Requisition } from "../types";

export default function RequisitionsPage() { const session = useSession(); const queryClient = useQueryClient(); const [params, setParams] = useSearchParams(); const [open, setOpen] = useState(params.get("new") === "1"); useEffect(() => { if (params.get("new") === "1") setOpen(true); }, [params]);
  const query = useQuery({ queryKey: ["requisitions"], queryFn: () => api<ListResponse<Requisition>>(session, "/api/v1/requisitions?limit=100") });
  const create = useMutation({ mutationFn: (payload: unknown) => post(session, "/api/v1/requisitions", payload), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ["requisitions"] }); setOpen(false); setParams({}); } });
  const close = () => { setOpen(false); setParams({}); };
  return <><PageHeader eyebrow="Demand" title="Requisitions" description="Shape purchase needs before they consume budget or enter the market." action={<button className="button button-primary" onClick={() => setOpen(true)}><Plus size={16}/>New requisition</button>}/>{query.isLoading ? <Loading/> : query.error ? <ErrorNotice error={query.error}/> : query.data!.items.length === 0 ? <EmptyState title="No requisitions yet" detail="Create the first request to begin a controlled purchase." action={<button className="button button-primary" onClick={() => setOpen(true)}>Create requisition</button>}/> : <section className="data-table-wrap"><table className="data-table"><thead><tr><th>Request</th><th>Department</th><th>Estimate</th><th>Need by</th><th>Status</th><th>Updated</th></tr></thead><tbody>{query.data!.items.map((item) => <tr key={item.id}><td><Link to={`/requisitions/${item.id}`}><strong>{item.title}</strong><span>REQ · v{item.version} · {item.lines.length} lines</span></Link></td><td>{item.department || "—"}</td><td>{money(item.lines.reduce((sum, line) => sum + Number(line.quantity) * Number(line.estimated_unit_price || 0), 0), item.currency)}</td><td>{item.need_by_date || "Not set"}</td><td><Status value={item.status}/></td><td>{relativeDate(item.updated_at)}</td></tr>)}</tbody></table></section>}
    <Dialog open={open} onClose={close} title="New requisition" description="Start with the purchasing need. Line detail can be refined while the request is in draft."><JsonForm onSubmit={(data) => create.mutate({ title: data.get("title"), justification: data.get("justification"), department: data.get("department") || null, cost_center: data.get("costCenter") || null, currency: data.get("currency"), need_by_date: data.get("needBy") || null, delivery_location: data.get("location") || null, lines: [{ line_number: 1, description: data.get("lineDescription"), quantity: data.get("quantity"), unit: data.get("unit"), estimated_unit_price: data.get("unitPrice") || null, alternatives_allowed: Boolean(data.get("alternatives")), specifications: {} }], requirements: [] })}><div className="form-grid"><Field label="Request title"><input name="title" required minLength={2} autoFocus/></Field><Field label="Department"><input name="department"/></Field><Field label="Business justification"><textarea name="justification" required minLength={2} rows={3}/></Field><Field label="Cost center"><input name="costCenter"/></Field><Field label="First line description"><input name="lineDescription" required/></Field><Field label="Quantity"><input name="quantity" required type="number" min="0.0001" step="any"/></Field><Field label="Unit"><input name="unit" required placeholder="each"/></Field><Field label="Estimated unit price"><input name="unitPrice" type="number" min="0" step="any"/></Field><Field label="Currency"><select name="currency" defaultValue="PKR"><option>PKR</option><option>USD</option><option>EUR</option></select></Field><Field label="Need-by date"><input name="needBy" type="date"/></Field><Field label="Delivery location"><input name="location"/></Field><label className="check-field"><input type="checkbox" name="alternatives"/><span>Allow equivalent alternatives</span></label></div>{create.error && <p className="form-error">{create.error.message}</p>}<FormActions pending={create.isPending} submit="Create draft" onCancel={close}/></JsonForm></Dialog></>;
}
