import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useSession } from "../auth/AuthContext";
import { Dialog, ErrorNotice, Field, FormActions, JsonForm, Loading, PageHeader, Status } from "../components/ui";
import { api, post } from "../lib/api";
import type { ListResponse, Supplier } from "../types";

type Rfq = { id: string; title: string; currency: string; status: string; version: number; publication_number: number; submission_deadline: string; terms: Record<string, unknown>; items: Array<{ id: string; description: string; quantity: string; unit: string }>; requirements: Array<{ id: string; priority: string; criterion: string }>; invitations: Array<{ id: string; supplier_id: string; status: string; rfq_revision_id: string | null; email_status: string; email_error_code: string | null }>; submissions: Array<{ id: string; supplier_id: string; version: number; status: string; lines: Array<{ rfq_item_id: string; quantity: string; unit_price: string }> }>; clarifications: Array<{ id: string; question: string; answer: string | null; status: string; visibility: string }> };

export default function RfqDetailPage() {
  const { id } = useParams(); const session = useSession(); const client = useQueryClient(); const [dialog, setDialog] = useState<"invite" | "amend" | "evaluate" | null>(null); const [error, setError] = useState(""); const [copied, setCopied] = useState("");
  const query = useQuery({ queryKey: ["rfq", id], queryFn: () => api<Rfq>(session, `/api/v1/rfqs/${id}`) });
  const suppliers = useQuery({ queryKey: ["suppliers"], queryFn: () => api<ListResponse<Supplier>>(session, "/api/v1/suppliers?limit=100"), enabled: dialog === "invite" || Boolean(query.data?.invitations.length) });
  const change = useMutation({ mutationFn: ({ path, body }: { path: string; body: unknown }) => post(session, path, body), onSuccess: () => { setError(""); setDialog(null); void client.invalidateQueries({ queryKey: ["rfq", id] }); void client.invalidateQueries({ queryKey: ["rfqs"] }); }, onError: reason => setError(reason instanceof Error ? reason.message : "Action failed") });
  if (query.isLoading) return <Loading/>; if (query.error || !query.data) return <ErrorNotice error={query.error}/>;
  const rfq = query.data;
  const act = (action: string, body: unknown) => change.mutate({ path: `/api/v1/rfqs/${id}/${action}`, body });
  return <><Link to="/sourcing" className="back-link">← Sourcing</Link><PageHeader eyebrow="Sourcing event" title={rfq.title} description={`Publication ${rfq.publication_number || "draft"} · Deadline ${new Date(rfq.submission_deadline).toLocaleString()}`} action={<Status value={rfq.status}/>}/>{error && <p className="form-error" role="alert">{error}</p>}
    <section className="panel" style={{ padding: 24, marginBottom: 20 }}><h2>Requirements</h2><ol>{rfq.items.map(item => <li key={item.id}>{item.description} — {item.quantity} {item.unit}</li>)}</ol>{rfq.requirements.map(item => <p key={item.id}><strong>{item.priority}:</strong> {item.criterion}</p>)}</section>
    <section className="panel" style={{ padding: 24, marginBottom: 20 }}><h2>Manage event</h2><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>{rfq.status === "draft" && <><button className="button button-ghost" onClick={() => setDialog("invite")}>Invite approved suppliers</button><button className="button button-primary" disabled={change.isPending || !rfq.invitations.length} onClick={() => act("publish", { expected_version: rfq.version })}>Publish RFQ</button></>}{rfq.status === "published" && <><button className="button button-ghost" onClick={() => setDialog("amend")}>Amend deadline or terms</button><button className="button button-primary" disabled={change.isPending || new Date(rfq.submission_deadline).getTime() > Date.now()} onClick={() => act("close", { expected_version: rfq.version })}>Close event</button></>}{rfq.status === "closed" && <button className="button button-primary" onClick={() => setDialog("evaluate")}>Evaluate current quotes</button>}{["draft", "published"].includes(rfq.status) && <button className="button button-ghost" disabled={change.isPending} onClick={() => { const reason = window.prompt("Cancellation reason"); if (reason) act("cancel", { expected_version: rfq.version, reason }); }}>Cancel</button>}</div></section>
    <section className="panel" style={{ padding: 24, marginBottom: 20 }}><h2>Invited suppliers</h2>{rfq.invitations.length === 0 && <p>Invite at least one approved supplier before publishing.</p>}{rfq.invitations.map(item => { const supplier = suppliers.data?.items.find(candidate => candidate.id === item.supplier_id); const link = `${window.location.origin}/supplier/invitations/${session.organizationId}/${item.id}`; return <p key={item.id}><strong>{supplier?.legal_name || item.supplier_id}</strong> · <Status value={item.status}/> · Email: <Status value={item.email_status}/> {item.email_error_code && <span>{item.email_error_code}</span>} {rfq.status === "published" && ["failed", "sent"].includes(item.email_status) && <button className="button button-ghost" disabled={change.isPending} onClick={() => change.mutate({ path: `/api/v1/rfq-invitations/${item.id}/send-email`, body: {} })}>Send email again</button>}{rfq.status !== "draft" && <button className="button button-ghost" onClick={() => { void navigator.clipboard.writeText(link).then(() => setCopied(item.id)); }}>{copied === item.id ? "Link copied" : "Copy supplier link"}</button>}</p>; })}<p className="page-description">Invitations are emailed to each supplier's primary registered contact on publication and amendment. The verified contact must sign in to respond; use the copy link only as a fallback.</p></section>
    <section className="panel" style={{ padding: 24, marginBottom: 20 }}><h2>Quotes</h2>{!rfq.submissions.length ? <p>No quotes received.</p> : rfq.submissions.map(item => <article key={item.id} style={{ borderTop: "1px solid var(--border)", padding: "12px 0" }}><strong>{suppliers.data?.items.find(candidate => candidate.id === item.supplier_id)?.legal_name || item.supplier_id}</strong> · Version {item.version} · <Status value={item.status}/><ul>{item.lines.map(line => <li key={line.rfq_item_id}>{rfq.items.find(product => product.id === line.rfq_item_id)?.description}: {line.quantity} × {line.unit_price} {rfq.currency}</li>)}</ul></article>)}</section>
    <section className="panel" style={{ padding: 24 }}><h2>Clarifications</h2>{rfq.clarifications.map(item => <article key={item.id}><p><strong>Q:</strong> {item.question} ({item.visibility})</p><p><strong>A:</strong> {item.answer || "Open"}</p>{item.status === "open" && <button className="button button-ghost" onClick={() => { const answer = window.prompt("Answer supplier question"); if (answer) change.mutate({ path: `/api/v1/rfqs/${id}/clarifications/${item.id}/answer`, body: { answer } }); }}>Answer</button>}</article>)}</section>
    <Dialog open={dialog === "invite"} title="Invite suppliers" description="Only approved supplier records can receive an RFQ invitation." onClose={() => setDialog(null)}><JsonForm onSubmit={data => act("invitations", { supplier_ids: data.getAll("supplier") })}>{suppliers.data?.items.filter(item => item.status === "approved" && !rfq.invitations.some(invite => invite.supplier_id === item.id)).map(item => <label className="check-field" key={item.id}><input type="checkbox" name="supplier" value={item.id}/>{item.legal_name}</label>)}<FormActions pending={change.isPending} submit="Add invitations" onCancel={() => setDialog(null)}/></JsonForm></Dialog>
    <Dialog open={dialog === "amend"} title="Amend RFQ" description="The new publication supersedes the previous revision for every supplier." onClose={() => setDialog(null)}><JsonForm onSubmit={data => act("amend", { expected_version: rfq.version, submission_deadline: new Date(String(data.get("deadline"))).toISOString(), terms: rfq.terms, reason: data.get("reason") })}><Field label="New deadline"><input name="deadline" type="datetime-local" required/></Field><Field label="Reason"><textarea name="reason" minLength={2} required/></Field><FormActions pending={change.isPending} submit="Publish amendment" onCancel={() => setDialog(null)}/></JsonForm></Dialog>
    <Dialog open={dialog === "evaluate"} title="Evaluate quotes" description="Record a human outcome and rationale for every controlled requirement in every current quote." onClose={() => setDialog(null)}><JsonForm onSubmit={data => change.mutate({ path: `/api/v1/rfqs/${id}/evaluations`, body: { expected_rfq_version: rfq.version, scoring_policy: { price_weight: Number(data.get("priceWeight")), preferred_weight: 1 - Number(data.get("priceWeight")) }, offers: rfq.submissions.filter(item => item.status === "submitted").map(item => ({ submission_id: item.id, checks: rfq.requirements.map(requirement => ({ requirement_id: requirement.id, outcome: data.get(`outcome-${item.id}-${requirement.id}`), rationale: data.get(`rationale-${item.id}-${requirement.id}`), evidence_anchor_ids: [] })) })) } })}><Field label="Price weight (0–1)"><input name="priceWeight" type="number" min="0" max="1" step="0.01" defaultValue="0.7" required/></Field>{rfq.submissions.filter(item => item.status === "submitted").map(item => <div key={item.id}><h3>{suppliers.data?.items.find(candidate => candidate.id === item.supplier_id)?.legal_name || item.supplier_id}</h3>{rfq.requirements.map(requirement => <div key={requirement.id}><p>{requirement.priority}: {requirement.criterion}</p><Field label="Outcome"><select name={`outcome-${item.id}-${requirement.id}`} required defaultValue="unknown"><option value="pass">Pass</option><option value="fail">Fail</option><option value="unknown">Unknown</option><option value="not_applicable">Not applicable</option></select></Field><Field label="Rationale"><textarea name={`rationale-${item.id}-${requirement.id}`} required minLength={2}/></Field></div>)}</div>)}<FormActions pending={change.isPending} submit="Create evaluation" onCancel={() => setDialog(null)}/></JsonForm></Dialog>
  </>;
}
