import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Save } from "lucide-react";
import { useSession } from "../auth/AuthContext";
import { ErrorNotice, Field, Loading, PageHeader } from "../components/ui";
import { api } from "../lib/api";
import type { Organization } from "../types";

type Settings = { id: string; version: number; settings: Record<string, unknown>; effective_from: string };
export default function SettingsPage() { const session = useSession(); const client = useQueryClient(); const org = useQuery({ queryKey: ["organization"], queryFn: () => api<Organization>(session, "/api/v1/organizations/current") }); const settings = useQuery({ queryKey: ["settings"], queryFn: () => api<Settings>(session, "/api/v1/organizations/current/settings") }); const save = useMutation({ mutationFn: (body: unknown) => api(session, "/api/v1/organizations/current/settings", { method: "PUT", body: JSON.stringify(body) }), onSuccess: () => void client.invalidateQueries({ queryKey: ["settings"] }) }); if (org.isLoading || settings.isLoading) return <Loading/>; if (org.error || (settings.error && (settings.error as { status?: number }).status !== 404)) return <ErrorNotice error={org.error || settings.error}/>; const current = settings.data?.settings || {};
  return <><PageHeader eyebrow="Workspace configuration" title="Organization settings" description="Changes create a new effective settings version; earlier values remain part of the audit trail."/><form className="settings-form" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); save.mutate({ settings: { currency: data.get("currency"), timezone: data.get("timezone"), fiscal_year_start: data.get("fiscalStart"), default_payment_terms_days: Number(data.get("paymentDays")), require_po_for_invoice: Boolean(data.get("requirePo")) } }); }}><section className="panel"><header className="panel-header"><div><p className="eyebrow">General</p><h2>{org.data?.name}</h2></div><span className="mono-label">v{settings.data?.version || 0}</span></header><div className="form-grid"><Field label="Default currency"><select name="currency" defaultValue={String(current.currency || org.data?.default_currency || "PKR")}><option>PKR</option><option>USD</option><option>EUR</option></select></Field><Field label="Business timezone"><input name="timezone" defaultValue={String(current.timezone || org.data?.timezone || "Asia/Karachi")}/></Field><Field label="Fiscal year starts"><input name="fiscalStart" type="date" defaultValue={String(current.fiscal_year_start || "")}/></Field><Field label="Default payment terms"><input name="paymentDays" type="number" min="0" defaultValue={Number(current.default_payment_terms_days || 30)}/></Field><label className="check-field full"><input name="requirePo" type="checkbox" defaultChecked={current.require_po_for_invoice !== false}/><span><strong>Require a purchase order for invoices</strong><small>Unsupported invoices must follow a separately authorized exception route.</small></span></label></div></section>{save.error && <p className="form-error">{save.error.message}</p>}<div className="settings-actions"><button className="button button-primary" disabled={save.isPending}><Save size={16}/>{save.isPending ? "Saving…" : "Save new version"}</button></div></form></>;
}
