import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarClock, Plus } from "lucide-react";
import { useState } from "react";
import { Link } from "react-router-dom";
import { useSession } from "../auth/AuthContext";
import { Dialog, EmptyState, ErrorNotice, Field, FormActions, JsonForm, Loading, PageHeader, Status } from "../components/ui";
import { api, post } from "../lib/api";
import { shortDate } from "../lib/format";
import type { ListResponse, Requisition, Rfq } from "../types";

export default function SourcingPage() { const session = useSession(); const client = useQueryClient(); const [open, setOpen] = useState(false); const query = useQuery({ queryKey: ["rfqs"], queryFn: () => api<ListResponse<Rfq>>(session, "/api/v1/rfqs?limit=100") }); const reqs = useQuery({ queryKey: ["requisitions"], queryFn: () => api<ListResponse<Requisition>>(session, "/api/v1/requisitions?limit=100") }); const create = useMutation({ mutationFn: (body: unknown) => post(session, "/api/v1/rfqs", body), onSuccess: () => { void client.invalidateQueries({ queryKey: ["rfqs"] }); setOpen(false); } });
  return <><PageHeader eyebrow="Competitive sourcing" title="RFQs and quotations" description="Publish controlled requirements and compare responses against the same revision." action={<button className="button button-primary" onClick={() => setOpen(true)}><Plus size={16}/>New RFQ</button>}/>{query.isLoading ? <Loading/> : query.error ? <ErrorNotice error={query.error}/> : !query.data?.items.length ? <EmptyState title="No sourcing events" detail="Create an RFQ from an approved requisition."/> : <section className="data-table-wrap"><table className="data-table"><thead><tr><th>RFQ</th><th>Deadline</th><th>Suppliers</th><th>Responses</th><th>Status</th></tr></thead><tbody>{query.data.items.map((item) => <tr key={item.id}><td><Link to={`/sourcing/${item.id}`}><strong>{item.title}</strong><span>Publication {item.publication_number || "draft"} · v{item.version}</span></Link></td><td><span className="with-icon"><CalendarClock size={15}/>{shortDate(item.submission_deadline)}</span></td><td>{item.invitations.length}</td><td>{item.submissions.length}</td><td><Status value={item.status}/></td></tr>)}</tbody></table></section>}
  <Dialog open={open} onClose={() => setOpen(false)} title="Create RFQ" description="The approved requisition lines and requirements are copied into a controlled sourcing event."><JsonForm onSubmit={(data) => create.mutate({ requisition_id: data.get("requisitionId"), title: data.get("title"), submission_deadline: new Date(String(data.get("deadline"))).toISOString(), terms: {} })}><Field label="Approved requisition"><select name="requisitionId" required defaultValue=""><option value="" disabled>Select a requisition</option>{reqs.data?.items.filter((r) => r.status === "approved").map((r) => <option value={r.id} key={r.id}>{r.title}</option>)}</select></Field><Field label="RFQ title"><input name="title" required autoFocus/></Field><Field label="Submission deadline"><input name="deadline" type="datetime-local" required/></Field>{create.error && <p className="form-error">{create.error.message}</p>}<FormActions pending={create.isPending} submit="Create draft RFQ" onCancel={() => setOpen(false)}/></JsonForm></Dialog></>;
}
