import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus, Store } from "lucide-react";
import { useState } from "react";
import { useSession } from "../auth/AuthContext";
import { api, post } from "../lib/api";
import type { ListResponse, Supplier } from "../types";
import { Dialog, EmptyState, ErrorNotice, Field, FormActions, JsonForm, Loading, PageHeader, Status } from "../components/ui";
import { relativeDate } from "../lib/format";

export default function SuppliersPage() { const session = useSession(); const client = useQueryClient(); const [open, setOpen] = useState(false); const query = useQuery({ queryKey: ["suppliers"], queryFn: () => api<ListResponse<Supplier>>(session, "/api/v1/suppliers?limit=100") }); const create = useMutation({ mutationFn: (body: unknown) => post(session, "/api/v1/suppliers", body), onSuccess: () => { void client.invalidateQueries({ queryKey: ["suppliers"] }); setOpen(false); } });
  return <><PageHeader eyebrow="Supply base" title="Suppliers" description="Qualification, contacts and evidence for every supplier relationship." action={<button className="button button-primary" onClick={() => setOpen(true)}><Plus size={16}/>Add supplier</button>}/>{query.isLoading ? <Loading/> : query.error ? <ErrorNotice error={query.error}/> : !query.data?.items.length ? <EmptyState title="No suppliers registered" detail="Add a supplier and complete qualification before inviting them to source."/> : <div className="card-grid">{query.data.items.map((item) => <article className="supplier-card" key={item.id}><header><div className="record-icon"><Store size={18}/></div><Status value={item.status}/></header><h3>{item.trading_name || item.legal_name}</h3><p>{item.legal_name}</p><div className="tag-row">{item.categories.slice(0, 3).map((category) => <span className="tag" key={category}>{category}</span>)}{!item.categories.length && <span className="tag muted">No categories</span>}</div><dl><div><dt>Registration</dt><dd>{item.registration_country} · {item.registration_number}</dd></div><div><dt>Qualification</dt><dd>{item.qualifications.filter((q) => q.status === "qualified").length} approved</dd></div><div><dt>Primary contact</dt><dd>{item.contacts.find((contact) => contact.is_primary)?.email || "Not assigned"}</dd></div></dl><SupplierActions supplier={item}/><footer>Updated {relativeDate(item.updated_at)}</footer></article>)}</div>}
  <Dialog open={open} onClose={() => setOpen(false)} title="Add supplier" description="Create the buyer-owned supplier record. Qualification remains a separate review."><JsonForm onSubmit={(data) => create.mutate({ legal_name: data.get("legalName"), trading_name: data.get("tradingName") || null, registration_country: data.get("country"), registration_number: data.get("registrationNumber"), tax_identifier: data.get("taxId") || null, website: data.get("website") || null, categories: String(data.get("categories") || "").split(",").map((x) => x.trim()).filter(Boolean), capabilities: {}, contacts: data.get("contactEmail") ? [{ name: data.get("contactName"), email: data.get("contactEmail"), phone: data.get("phone") || null, title: data.get("contactTitle") || null, is_primary: true }] : [] })}><div className="form-grid"><Field label="Legal name"><input name="legalName" required autoFocus/></Field><Field label="Trading name"><input name="tradingName"/></Field><Field label="Registration country" hint="Two-letter ISO code"><input name="country" required pattern="[A-Z]{2}" defaultValue="PK"/></Field><Field label="Registration number"><input name="registrationNumber" required/></Field><Field label="Tax identifier"><input name="taxId"/></Field><Field label="Website"><input name="website" type="url"/></Field><Field label="Categories" hint="Comma separated"><input name="categories" placeholder="IT hardware, Managed services"/></Field><div/><Field label="Primary contact name"><input name="contactName"/></Field><Field label="Primary contact email"><input name="contactEmail" type="email"/></Field><Field label="Job title"><input name="contactTitle"/></Field><Field label="Phone"><input name="phone"/></Field></div>{create.error && <p className="form-error">{create.error.message}</p>}<FormActions pending={create.isPending} submit="Add supplier" onCancel={() => setOpen(false)}/></JsonForm></Dialog></>;
}

function SupplierActions({ supplier }: { supplier: Supplier }) {
  const session = useSession(); const client = useQueryClient(); const [error, setError] = useState("");
  const change = useMutation({ mutationFn: ({ path, body }: { path: string; body: unknown }) => post<Supplier>(session, `/api/v1/suppliers/${supplier.id}${path}`, body), onSuccess: () => { setError(""); void client.invalidateQueries({ queryKey: ["suppliers"] }); }, onError: reason => setError(reason instanceof Error ? reason.message : "Action failed") });
  return <div style={{ display: "flex", gap: 6, flexWrap: "wrap" }}>{error && <p className="form-error">{error}</p>}
    <button className="button button-ghost" disabled={change.isPending} onClick={() => { const category = window.prompt("Qualification category"); if (category) change.mutate({ path: "/qualifications", body: { category } }); }}>Add qualification</button>
    {supplier.qualifications.filter(item => item.status === "pending").map(item => <button key={item.id} className="button button-ghost" disabled={change.isPending} onClick={() => { const validTo = window.prompt(`Valid-to date for ${item.category} (YYYY-MM-DD)`); if (validTo) change.mutate({ path: `/qualifications/${item.id}/decision`, body: { status: "qualified", valid_from: new Date().toISOString().slice(0, 10), valid_to: validTo, assessment_notes: "Reviewed by buyer" } }); }}>Qualify {item.category}</button>)}
    {supplier.status !== "approved" && <button className="button button-primary" disabled={change.isPending} onClick={() => change.mutate({ path: "/approve", body: { expected_version: supplier.version, reason: "Qualification reviewed" } })}>Approve supplier</button>}
    {supplier.status === "approved" && <button className="button button-ghost" disabled={change.isPending} onClick={() => { const reason = window.prompt("Suspension reason"); if (reason) change.mutate({ path: "/suspend", body: { expected_version: supplier.version, reason } }); }}>Suspend</button>}
  </div>;
}
