import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Link } from "react-router-dom";
import { useSession } from "../auth/AuthContext";
import { Field, JsonForm, Status } from "../components/ui";
import { api, post } from "../lib/api";
import type { ListResponse } from "../types";
import type { Policy } from "./ApprovalsPage";

type Scenario = { id: string; status: string; content_digest: string; objective_amount: string | null; allocations: Array<{ supplier_id: string }> };
type OrderLine = { id: string; description: string; quantity: string; unit_price: string; tax_amount: string; freight_amount: string };
type Receipt = { id: string; receipt_number: string; lines: Array<{ id: string; purchase_order_line_id: string; accepted_quantity: string; returned_quantity: string }> };
type Match = { id: string; attempt: number; outcome: string; exceptions: Array<{ id: string; message: string; resolved_at: string | null; resolution: string | null }> };

export default function WorkflowActions({ type, id, record }: { type: string; id: string; record: Record<string, unknown> }) {
  const session = useSession(); const client = useQueryClient(); const [error, setError] = useState("");
  const status = String(record.status || ""); const digest = String(record.content_digest || ""); const version = Number(record.version || 0);
  const evaluationId = type === "evaluation" ? id : String(record.evaluation_id || "");
  const scenarios = useQuery({ queryKey: ["scenarios", evaluationId], queryFn: () => api<ListResponse<Scenario>>(session, `/api/v1/evaluations/${evaluationId}/allocation-scenarios`), enabled: (type === "evaluation" || type === "award") && Boolean(evaluationId) });
  const policies = useQuery({ queryKey: ["approval-policies"], queryFn: () => api<ListResponse<Policy>>(session, "/api/v1/approval-policies"), enabled: type === "evaluation" });
  const receipts = useQuery({ queryKey: ["receipts", id], queryFn: () => api<Receipt[]>(session, `/api/v1/purchase-orders/${id}/receipts`), enabled: type === "purchase-order" });
  const matches = useQuery({ queryKey: ["matches", id], queryFn: () => api<Match[]>(session, `/api/v1/invoices/${id}/matches`), enabled: type === "invoice" });
  const change = useMutation({ mutationFn: ({ path, body }: { path: string; body: unknown }) => post<Record<string, unknown>>(session, path, body), onSuccess: () => { setError(""); void client.invalidateQueries({ queryKey: ["record", type, id] }); void client.invalidateQueries({ queryKey: ["scenarios", evaluationId] }); void client.invalidateQueries({ queryKey: ["lookup"] }); void client.invalidateQueries({ queryKey: ["matches", id] }); void client.invalidateQueries({ queryKey: ["receipts", id] }); }, onError: reason => setError(reason instanceof Error ? reason.message : "Action failed") });
  const send = (path: string, body: unknown) => change.mutate({ path: `/api/v1${path}`, body });
  const current = record.current as { lines?: OrderLine[] } | undefined;
  const lines = current?.lines || [];
  const selectedScenario = scenarios.data?.items.find(item => item.id === record.allocation_scenario_id);
  return <section className="panel" style={{ padding: 24, marginTop: 20 }}><h2>Workflow actions</h2>{error && <p className="form-error" role="alert">{error}</p>}
    {type === "evaluation" && <><p>Offers in this evaluation: {Array.isArray(record.offers) ? record.offers.length : 0}</p><JsonForm onSubmit={data => send(`/evaluations/${id}/allocation-scenarios`, { name: data.get("name"), expected_evaluation_digest: digest, allow_split_awards: Boolean(data.get("split")) })}><Field label="Allocation scenario name"><input name="name" required defaultValue="Best value"/></Field><label className="check-field"><input type="checkbox" name="split" defaultChecked/>Allow split award</label><button className="button button-primary" disabled={change.isPending}>Calculate allocation</button></JsonForm>{scenarios.data?.items.map(item => <article key={item.id}><p><strong>Scenario {item.id.slice(0, 8)}</strong> · <Status value={item.status}/> · {item.objective_amount || "No feasible result"}</p>{item.status === "optimal" || item.status === "feasible" ? <JsonForm onSubmit={data => send(`/allocation-scenarios/${item.id}/awards`, { expected_scenario_digest: item.content_digest, recommendation: data.get("recommendation"), approval_policy_id: data.get("policy") })}><Field label="Recommendation"><textarea name="recommendation" required minLength={10}/></Field><Field label="Approval policy"><select name="policy" required><option value="">Select policy</option>{policies.data?.items.filter(policy => policy.status === "active").map(policy => <option key={policy.id} value={policy.id}>{policy.name}</option>)}</select></Field><button className="button button-primary" disabled={change.isPending}>Prepare award</button></JsonForm> : null}</article>)}</>}
    {type === "award" && <>{status === "draft" && <button className="button button-primary" disabled={change.isPending} onClick={() => send(`/awards/${id}/submit`, { expected_content_digest: digest })}>Submit award for approval</button>}{status === "pending_approval" && <div style={{ display: "flex", gap: 8 }}><button className="button button-primary" disabled={change.isPending} onClick={() => send(`/awards/${id}/approve`, { expected_content_digest: digest, comment: "Approved after dossier review" })}>Approve award</button><button className="button button-ghost" disabled={change.isPending} onClick={() => { const comment = window.prompt("Rejection reason"); if (comment) send(`/awards/${id}/reject`, { expected_content_digest: digest, comment }); }}>Reject</button></div>}{status === "approved" && selectedScenario && <><h3>Prepare purchase orders</h3>{[...new Set(selectedScenario.allocations.map(item => item.supplier_id))].map(supplierId => <button key={supplierId} className="button button-primary" disabled={change.isPending} onClick={() => send(`/awards/${id}/purchase-orders`, { supplier_id: supplierId, expected_award_digest: digest, idempotency_key: crypto.randomUUID() })}>Create PO for supplier {supplierId.slice(0, 8)}</button>)}</>}</>}
    {type === "purchase-order" && <>{["draft", "authorized"].includes(status) && <button className="button button-primary" disabled={change.isPending} onClick={() => send(`/purchase-orders/${id}/issue`, { expected_version: version, expected_content_digest: digest })}>Issue purchase order</button>}{status === "issued" && <div><p>Send this scoped link to the registered supplier contact for direct acknowledgement.</p><button className="button button-ghost" onClick={() => void navigator.clipboard.writeText(`${window.location.origin}/supplier/orders/${session.organizationId}/${id}`)}>Copy supplier order link</button></div>}{["acknowledged", "partially_received"].includes(status) && <JsonForm onSubmit={data => send(`/purchase-orders/${id}/receipts`, { expected_po_version: version, idempotency_key: crypto.randomUUID(), received_at: new Date().toISOString(), lines: lines.map(line => ({ purchase_order_line_id: line.id, accepted_quantity: data.get(`qty-${line.id}`), rejected_quantity: 0 })) })}><h3>Record receipt</h3>{lines.map(line => <Field key={line.id} label={`Accepted: ${line.description}`}><input name={`qty-${line.id}`} type="number" min="0" step="0.0001" defaultValue={line.quantity} required/></Field>)}<button className="button button-primary" disabled={change.isPending}>Record delivery</button></JsonForm>}{["acknowledged", "partially_received", "received"].includes(status) && <JsonForm onSubmit={data => { const invoiceLines = lines.map(line => ({ purchase_order_line_id: line.id, description: line.description, quantity: line.quantity, unit_price: line.unit_price, tax_amount: line.tax_amount, freight_amount: line.freight_amount })); const subtotal = invoiceLines.reduce((sum, line) => sum + Number(line.quantity) * Number(line.unit_price), 0); const tax = invoiceLines.reduce((sum, line) => sum + Number(line.tax_amount), 0); const freight = invoiceLines.reduce((sum, line) => sum + Number(line.freight_amount), 0); send(`/purchase-orders/${id}/invoices`, { supplier_invoice_number: data.get("invoiceNumber"), invoice_date: data.get("invoiceDate"), currency: record.currency, subtotal, tax_amount: tax, freight_amount: freight, total_amount: subtotal + tax + freight, idempotency_key: crypto.randomUUID(), lines: invoiceLines }); }}><h3>Capture supplier invoice</h3><Field label="Supplier invoice number"><input name="invoiceNumber" required/></Field><Field label="Invoice date"><input name="invoiceDate" type="date" required/></Field><button className="button button-primary" disabled={change.isPending}>Capture invoice</button></JsonForm>}</>}
    {type === "purchase-order" && receipts.data?.map(receipt => <article key={receipt.id}><h3>Receipt {receipt.receipt_number}</h3>{receipt.lines.map(line => <p key={line.id}>Accepted {line.accepted_quantity}; returned {line.returned_quantity} <button className="button button-ghost" onClick={() => { const quantity = window.prompt("Quantity to return"); const reason = quantity && window.prompt("Return reason"); if (quantity && reason) send(`/receipt-lines/${line.id}/returns`, { quantity, reason, idempotency_key: crypto.randomUUID(), returned_at: new Date().toISOString() }); }}>Record return</button></p>)}</article>)}
    {type === "invoice" && <>{["captured", "mismatch"].includes(status) && <button className="button button-primary" disabled={change.isPending} onClick={() => send(`/invoices/${id}/match`, { expected_invoice_version: version, mode: "three_way", idempotency_key: crypto.randomUUID() })}>Run three-way match</button>}{matches.data?.map(match => <article key={match.id}><h3>Match attempt {match.attempt}: <Status value={match.outcome}/></h3>{match.exceptions.map(item => <p key={item.id}>{item.message} · {item.resolved_at ? `Resolved: ${item.resolution}` : <button className="button button-ghost" disabled={change.isPending} onClick={() => { const resolution = window.prompt("Explain how this exception was resolved"); if (resolution) send(`/match-exceptions/${item.id}/resolve`, { expected_invoice_version: version, resolution }); }}>Resolve exception</button>}</p>)}</article>)}{status === "matched" && <button className="button button-primary" disabled={change.isPending} onClick={() => send(`/invoices/${id}/approve-for-export`, { expected_invoice_version: version })}>Approve for export</button>}{status === "approved_for_export" && <button className="button button-primary" disabled={change.isPending} onClick={() => send(`/invoices/${id}/accounting-exports`, { expected_invoice_version: version, idempotency_key: crypto.randomUUID() })}>Create accounting export</button>}</>}
    {!["evaluation", "award", "purchase-order", "invoice"].includes(type) && <p>Open the dedicated record workspace for available actions.</p>}{type === "award" && <Link to="/operations">View purchase orders</Link>}
  </section>;
}
